### ISSUE TITLE
subPropertyOf element is ignored

### ISSUE THREAD

**Issue by BonaBeavis** [oeg-upm/Chowlk#21]
Both forms of the `subPropertyOf` do not appear in the ouput.

**Comment by Serge3006** [comment]
Hi, have you verified that the arrows are properly connected to the rhombuses? I've tried the following and works well:

![image](https://user-images.githubusercontent.com/30761241/129563543-1462c300-476a-403c-8b44-61cdc56c7fd5.png)

Could you please send me a snapshot of that part of your diagram?

**Comment by BonaBeavis** [comment]
For the rhombus version the issue was that the template from the library has no namespace prefix for the object properties. So I added them, and it worked.

The error version still does not work, I can not get the error to connect. I drag an end but no anchor points appear.
![grafik](https://user-images.githubusercontent.com/3330855/129754700-e707fe9f-0120-4ee9-8067-343e859d3ad7.png)

**Comment by Serge3006** [comment]
Yes, thank you for spotting that in the diamonds. In the case of the arrow version, it is not supported by the converted, because we are restricted from the diagrams.net tool to attached arrows to other arrows. It is indicated in the instructions of the converter, but is true that it should be indicated more explicitly in the specification.

![image](https://user-images.githubusercontent.com/30761241/129884043-62b233a7-5ff4-4e9e-9fe6-08fe60c521bb.png)

**Comment by BonaBeavis** [comment]
Okay sorry for the "rtfm" issue. But why don't you just remove option 2?
