### ISSUE TITLE
Namespace for datatype range is always xds

### ISSUE THREAD

**Issue by GordianDziwis** [oeg-upm/Chowlk#39]
This diagram:
![image](https://user-images.githubusercontent.com/3330855/194766973-180fc6ec-c401-4469-8a2e-56bf19d2c229.png)

Should output this:
```turtle
```turtle
ns:datatypeProperty1 a owl:DatatypeProperty ;
    rdfs:label "datatype property1" ;
    rdfs:range ns:test .
```

Instead of:
```turtle
ns:datatypeProperty1 a owl:DatatypeProperty ;
    rdfs:label "datatype property1" ;
    rdfs:range xsd:ns .
```

**Comment by mariapoveda** [comment]
Initally it was intended only for xsd. We'll consider it as future feature.

**Comment by Sergio-Carulli** [comment]
Now custom datatypes can be defined. By default, if a prefix is not defined, "xsd" is taken as the datatype prefix. In order to use custom datatypes please see https://chowlk.linkeddata.es/notation.html#datatype-properties , https://chowlk.linkeddata.es/notation.html#restriction-value-constraint-identifier , https://chowlk.linkeddata.es/notation.html#datatype-properties-enumerated-datatype and https://chowlk.linkeddata.es/notation.html#property-values
