### ISSUE TITLE
Cardinality ranges

### ISSUE THREAD

**Issue by jordanasalamon** [oeg-upm/Chowlk#62]
Hi,

I recently started to use Chowlk to develop my ontologies, but for some reason the cardinalities are not being translated correctly in my case.
If I have in the model the following relationship:
Class1 has_x (1..N) Class2
The translated owl file only gives me the following axiom:
Class1 has_x min 1 owl:Thing

This happens with arrows with domain and range and arrows without domain and range.
Is there something that I am missing here? Or doing wrong?
Screenshots were included to help understand the problem.

![Screenshot 2023-11-28 173605](https://github.com/oeg-upm/Chowlk/assets/8644607/e6caf00b-aed0-4dc9-adb2-591fc3ff60d9)
![Screenshot 2023-11-28 173629](https://github.com/oeg-upm/Chowlk/assets/8644607/412a025f-1fe5-4523-a2a6-f98c5f0f5db7)

Thank you for your time and consideration.

**Comment by Sergio-Carulli** [comment]
Hi,

Currently only owl 1 cardinality constraints are allowed to be created in chowlk (https://www.w3.org/TR/owl-ref/#CardinalityRestriction). I think you are trying to declared owl 2 qualified cardinalities (https://www.w3.org/TR/owl2-syntax/#Object_Property_Cardinality_Restrictions). Qualified cardinalities are not yet in chowlk, but we are currently working on the notation to add them as soon as possible.

The style of the arrows (arrows with domain and range, arrows without domain and range, etc) . It only affects the declaration of the properties (in order to indicate if they must be declared with domain and/or range).

Thanks for using chowlk.

**Comment by jordanasalamon** [comment]
Hi,

Thank you for the answer!

**Comment by Sergio-Carulli** [comment]
Qualified Cardinalities have been implemented and added to the library which you can download from the Chowlk main page or https://chowlk.linkeddata.es/static/resources/chowlk-library-complete.xml

To see how to use them please see https://chowlk.linkeddata.es/notation.html#restriction-qualified-cardinality-constraint-identifier
